# Generated by Django 4.1.7 on 2023-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('username', models.CharField(max_length=55)),
                ('familiya', models.CharField(max_length=55)),
                ('tugilgan_yil', models.DateTimeField()),
                ('subject', models.CharField(choices=[('Til', 'Til'), ('Aniq fanlar', 'Aniqfanlar'), ('Dasturlash', 'Dasturlash'), ('Tabiy fanlar', 'Tabiyfanlar')], default='Tabiy fanlar', max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('telegramORnumber', models.CharField(max_length=13)),
                ('tajriba', models.CharField(max_length=20)),
                ('qayerda_oqigan', models.CharField(max_length=55)),
                ('language', models.CharField(choices=[('Ingliz', 'Ingliz'), ('Rustili', 'Rustili'), ('Koreystili', 'Python'), ('Yapontili', 'Java'), ('Matematika', 'Matematika'), ('Fizika', 'Fizlika'), ('Biologiya', 'Biologiya'), ('Kimyo', 'Kimyo')], default='Biologiya', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('resume', models.FileField(upload_to='resume/')),
                ('sertificat', models.FileField(upload_to='resume/')),
                ('address', models.CharField(max_length=155)),
                ('descrption', models.TextField(max_length=1000)),
            ],
        ),
    ]
